travis:
  secure:
    BINSTAR_TOKEN: MjRuU7Q8Q+8/F7BbdW6uMTMcmG2NWvBAR6ETXkExF3Mn99lGqAnYGKPl9FRiosmsINOgeCGZDd0S8GvjZMuuvQjxN35plC9AnpQiBAkBW2bcMtrgvJhJpSQCovsOq4lB7S5j6noVxynE89uNAFAzddRJwlJ3w7MLeveWnnJavFC1AwjjFYMulUFRuPKGW8jc6aJoUlofttgObrsiipEEtL8YjTculOiBHPW2BvhO1aikaHAqBIa4urN0wRyNu8T3EfC5KJGBZZyDc3oKcWrCqWb3ojRGG0L6NSLEwSyyeZDdrfJBwF+3Ay5B8m+7ljN1iYe2i09jtlBHXgDRpsxqWUEpNaEDMi8r9AdpqXqM7jx0i9Id7gm1GY/f1PD2RdiHGAH/4rQyadm5e476mrbXwqwYjY92y+hqrusRrwuA5+AhfXByquZvHe+ngjTwVRdmozVl0BZ2MNGi3xaheGGfGBK/+5YAV64h1cIbyGyWkr1gD4jTwbaxem/4WgJKjL4T6qrxz5RY1u0MM6IdibNRQi0hFHnf9SKIj3uIa48YjFy0b4w4GWcXre9zEeRupoWPe2QPuNd8oQoBguPLBvrbVggO3HY6Jnnd8qqRQwhzUQwHayzg7/h7mawQ1ZXe017//1SZ1may6kyrLR3+e1tOhJoeOEoXsJWwvk22F5ESP8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
